(defun clock()
  (charms:initscr)
  (charms:clear)
  (charms:curs-set 0)
  (loop with start = (get-universal-time)
       do (multiple-value-bind (s m h) (get-decoded-time)
	    (charms:mvaddstr 0 0 (format nil "~2,'0d:~2,'0d:~2,'0d" h m s)))
       (charms:refresh)
       until (>= (- (get-universal-time) start) 10))
  (charms:endwin))
