(defun sample-pdf(&optional (file #P"~/samppdf.pdf"))
  (pdf:with-document ()
    (pdf:with-page()
      (pdf:with-outline-level ("EXample" (pdf:register-page-reference))
	(let ((helvetica (pdf:get-font "Helvetica")))
	  (pdf:in-text-mode
	    (pdf:set-font helvetica 36.0)
	    (pdf:move-text 100 800)
	    (pdf:draw-text "Tamils First Example Go Easy"))
	  (pdf:set-rgb-stroke 0.1 0.1 0.1)
	  (pdf:set-rgb-fill 0.8 0.8 0.8)
	  (let ((x 50)
		(y 600))
	    (dotimes (i 2)
	      (pdf:rectangle x y 500 140 :radius 10)
	      (pdf:close-fill-and-stroke)
	      (setf y (- y 180)))))))
      (pdf:write-document  file)))
	  